### ISSUE TITLE
Give some use to the version file

### ISSUE THREAD

**Issue by inkatze** [inkatze/wildfly#17]
The version file created by the install part of the role should be used for the following purposes:

- Maintain role's idempotency preventing reinstalling the service when it already exists.
- ~~Implement a CI workflow that takes advantage of the idempotency.~~

I think for now the first point is doable and it'll reduce the installation time since it won't even download wildfly when it detects a successful installation with the same version.

**Comment by kostyrev** [comment]
Sorry to bother but I think the first point would be resolved via #15

**Comment by inkatze** [comment]
Updated the description so it fits with the changes in #15 and it can be resolved after the PR is merged.

**Comment by inkatze** [comment]
Resolved in #15
