### ISSUE TITLE
Using init.d script shipped by upstream

### ISSUE THREAD

**Issue by kostyrev** [inkatze/wildfly#22]
Is there any issues with using init.d script that wildfly team ships with the tar.gz?
I took a look at the differences and they are:

```
# diff -U2 /opt/wildfly/bin/init.d/wildfly-init-redhat.sh /etc/init.d/wildfly
--- /opt/wildfly/bin/init.d/wildfly-init-redhat.sh	2015-07-24 00:27:14.000000000 +0000
+++ /etc/init.d/wildfly	2016-12-02 15:27:00.841649817 +0000
@@ -19,5 +19,5 @@
 # Load JBoss AS init.d configuration.
 if [ -z "$JBOSS_CONF" ]; then
-	JBOSS_CONF="/etc/default/wildfly.conf"
+	JBOSS_CONF="/etc/wildfly/wildfly.conf"
 fi
 
@@ -71,4 +71,14 @@
 prog='wildfly'
 
+CMD_PREFIX=''
+
+if [ ! -z "$JBOSS_USER" ]; then
+	if [ -r /etc/rc.d/init.d/functions ]; then
+		CMD_PREFIX="daemon --user $JBOSS_USER"
+	else
+		CMD_PREFIX="su - $JBOSS_USER -c"
+	fi
+fi
+
 start() {
 	echo -n "Starting $prog: "
@@ -89,6 +99,9 @@
 	mkdir -p $(dirname $JBOSS_PIDFILE)
 	chown $JBOSS_USER $(dirname $JBOSS_PIDFILE) || true
+	#$CMD_PREFIX JBOSS_PIDFILE=$JBOSS_PIDFILE $JBOSS_SCRIPT 2>&1 >> $JBOSS_CONSOLE_LOG &
+	#$CMD_PREFIX JBOSS_PIDFILE=$JBOSS_PIDFILE $JBOSS_SCRIPT &
+
 
-	if [ ! -z "$JBOSS_USER" ]; then
+    if [ ! -z "$JBOSS_USER" ]; then
 		if [ "$JBOSS_MODE" = "standalone" ]; then
 			if [ -r /etc/rc.d/init.d/functions ]; then
```

1) some strange stuff with `CMD_PREFIX`. It is defined but never used. Is there any necessity in it?
2) If the role would render `wildfly.conf.j2` to `/etc/default/wildfly.conf` there will be no need to have `wildfly.init.j2` at all.

Why shipping `wildfly.init.j2`  might be an issue?
The developers might change init.d script in wildfly 9, 10, 11 and so on. So this `wildfly.init.j2` must be manually altered to incorporate upstream changes.

What do you think?

**Comment by inkatze** [comment]
I agree, this is something that should be added. What I did is to add the latest conf file available at the time (I think it was wildlfy 9) which may not work with previous or future versions, because it was the easiest and **quickest** solution.
