### ISSUE TITLE
Variables wildfly_user and wildfly_group not honoured in systemctl service file

### ISSUE THREAD

**Issue by MiguelGL** [inkatze/wildfly#40]
Hi, thanks for this role first of all :)

The `templates/wildfly.service.j2` has the hardcoded `wildfly` value for both `User` and `Group`. I think they should be set to the role variables `{{ wildfly_user }}` and `{{ wildfly_group }}` like this:

```
...
[Service]
...
User={{ wildfly_user }}
Group={{ wildfly_group }}
...
```

**Comment by kostyrev** [comment]
Care to send PR?

**Comment by inkatze** [comment]
Thanks for letting us now :) Feel free to send a PR if you find another issue like this in the future; I took this one because I had a little bit of extra time, but that rarely happens.

Cheers.

**Comment by MiguelGL** [comment]
Indeed, I should've PR'ed, sorry -- will do for any further issue. 

Thanks!
