### ISSUE TITLE
wildfly_management_user variable should be wildfly_management_users in documentation

### ISSUE THREAD

**Issue by onitake** [inkatze/wildfly#54]
The README mentions a wildfly_management_user variable, but in the defaults and Ansible tasks, wildfly_management_users (a list) is used.

The documentation should be updated to reflect this.

**Comment by kostyrev** [comment]
PRs are welcomed :-)

**Comment by onitake** [comment]
Here you go, please review.

I removed some other parts that are no longer relevant as well.
